[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[project]
name = "repid"
description = "Repid framework: simple to use, fast to run and extensible to adopt job scheduler"
authors = [{ name = "aleksul", email = "me@aleksul.space" }]
dependencies = [
    "orjson>=3.7.11,<4.0.0",
    "typing-extensions>=4.3.0,<5.0.0; python_version < \"3.10\"",
]
requires-python = ">=3.8"
readme = "README.md"
dynamic = ["version"]
license = { text = "MIT" }

[project.optional-dependencies]
amqp = ["aiormq<7.0.0,>=6.4.0"]
redis = ["redis<5.0.0,>=4.3.3"]
cron = ["croniter<2.0.0,>=1.3.4"]

[project.urls]
repository = "https://github.com/aleksul/repid"
documentation = "https://repid.aleksul.space"
funding = "https://github.com/sponsors/aleksul"
tracker = "https://github.com/aleksul/repid/issues"

[tool.black]
line-length = 100

[tool.coverage]

[tool.coverage.report]
fail_under = 90
exclude_lines = [
    '\.\.\.',
    'if TYPE_CHECKING:',
    'pragma: no cover',
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
exclude = ["benchmarks"]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_any_unimported = false

[[tool.mypy.overrides]]
module = ["pytest_docker_tools", "pytest_lazyfixture"]
ignore_missing_imports = true

[tool.pdm]
version = { source = "scm" }

[tool.pdm.build]
includes = ["repid"]

[tool.pdm.dev-dependencies]
format = ["black", "isort"]
lint = [
    "mypy",
    "types-orjson",
    "types-redis",
    "types-croniter",
    "ruff",
]
tests = [
    "pytest",
    "pytest-asyncio",
    "pytest-pretty",
    "pytest-clarity",
    "pytest-lazy-fixture",
    "pytest-docker-tools",
    "pytest-cov",
    "hypothesis",
    "pydantic<2.0.0,>=1.10.0",
]
pre-commit = ["pre-commit"]
docs = ["mkdocs-material", "mike", "setuptools>=65.5.1"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
select = ["F", "E", "B", "A", "RUF", "S", "W"]
line-length = 100
ignore = ["S101", "B905"]
per-file-ignores = { "tests/*" = ["S"], "repid/connections/__init__.py" = ["F401"] }
